### ISSUE TITLE
Not getting proper data in webhook responce

### ISSUE THREAD

**Issue by prasenforu** [cipher-co/kubewatch#7]
I am running kubewatch in Openshift 3.11

With POD creation event not showing proper namespace.

Sometimes it's taking namespace where kubewatch is running even all update events also taking same where kubewatch is running.

Sometimes it's taking namespace when I switch to namespace (oc project <namespace>) even all update events also taking same where I switch to namespace (oc project <namespace>).

**Comment by codenio** [comment]
Working on it, will update the fix here

**Comment by prasenforu** [comment]
please find example .....

![image](https://user-images.githubusercontent.com/19322497/62108283-4ce7b380-b2c7-11e9-9f77-e897ca1a850b.png)

**Comment by prasenforu** [comment]
with some example ...

![image](https://user-images.githubusercontent.com/19322497/62108408-989a5d00-b2c7-11e9-8cb8-e2df330eff0f.png)

**Comment by codenio** [comment]
PR #8 fixes this

![Screenshot_2019-07-30-13-08-34-610_com brave browser](https://user-images.githubusercontent.com/30741615/62110096-4a875880-b2cb-11e9-8407-70d4c5adcfe5.png)

**Comment by codenio** [comment]
Do verify with the latest image from docker hub, and let us know

**Comment by prasenforu** [comment]
No !! same as earlier ..... 

![image](https://user-images.githubusercontent.com/19322497/62111815-0f872400-b2cf-11e9-99d6-6984b92856fd.png)

it's taking namespace where kubewatch is running even all update events also taking same where kubewatch is running.

![image](https://user-images.githubusercontent.com/19322497/62112013-773d6f00-b2cf-11e9-8b92-830b79196306.png)

**Comment by codenio** [comment]
Does the docker image runs with the latest code. I verified it from my local and it was working fine. 
Will check again.

**Comment by prasenforu** [comment]
yes !! 

I deleted old images. 

behavior is not all time.

**Comment by codenio** [comment]
Merged the fix with the master. Do verify.

**Comment by codenio** [comment]
Hi, @prasenforu once verified we can close this issue.

**Comment by prasenforu** [comment]
OK
